### ISSUE TITLE
[Unknown issue] players cant connect to the server on conjuring fabric 0.2.3

### ISSUE THREAD

**Issue by LordDecay26** [glisco03/conjuring#11]
dunno if this issue is fixed already, but i need a quick solution to it ASAP

here's my server log
https://pastebin.com/v4E9X3Rq

here's my client log
https://pastebin.com/En9U5YgR

here's a screenshot of the error that comes up
https://cdn.discordapp.com/attachments/817103391129468940/858011031657250846/unknown.png

please help

**Comment by glisco03** [comment]
I have never seen this before from Conjuring, but I would assume that you're not running the same version on server and client

**Comment by LordDecay26** [comment]
actually nevermind, false alarm
