### ISSUE TITLE
Gem tinker disappears

### ISSUE THREAD

**Issue by Hero9909** [glisco03/conjuring#12]
version 1.0.3 beta mc 1.17 fabric 11.3
upon initiating the crafting progress for a haste gem the tinkerer and its resources disapears

**Comment by Spacecooki** [comment]
I have the same problem, but with both Emeralds, Eyes, Rubys and Lapis

**Comment by gliscowo** [comment]
I would suspect Carrier being at fault here. Try either disabling it or putting your keybind on something other than shift

**Comment by Spacecooki** [comment]
Tried to swap the "sneak" from shift to another keybinding but the whole thing still dissapears.
When I sneak to press it, I suddenly collect all of the gems but the lesser soul essence is still left. So I try to put the gems back but as soon as I do that the whole thing dissapears

**Comment by gliscowo** [comment]
You're obviously having some kind of incompatibility, you'll have to go and find out which mod is causing it

**Comment by Noaaan** [comment]
Does disabling Carry fix the issue?

**Comment by AGUrGrill** [comment]
I am having the same issue with version 1.0.5 on fabric.

**Comment by gliscowo** [comment]
> Does disabling Carry fix the issue?

Has anyone who is affected by this problem tried this?

**Comment by AGUrGrill** [comment]
I did not realize that was a mod lol. After changing its keybind everything works as intended, thanks!

**Comment by gliscowo** [comment]
Seeing as every other known case of this was caused by Carrier and the fact the original author hasnt responded in over a month I will now close this as resolved
