### ISSUE TITLE
Incompatibility with Not Enough Animations - Crash & Failed to Save Chunk Error when interacting with Gem Tinkerer with Totem of Undying

### ISSUE THREAD

**Issue by ConqAra** [glisco03/conjuring#15]
(tested for 1.16.5 version) In a server, Right clicking a gem tinkerer while having a totem of undying in your offhand will pretty much DESTROY the chunk the gem tinkerer is in. It completely crashes the player and requires a server restart to get the player back in. As soon as you load back into the server, the chunk the gem tinkerer was at will completely reset the chunk, getting rid of everything in it. This is a major problem as most people literally have Totem of undyings in their offhand and I ended up putting the gem tinkerer in my house so yeah, massive bug.

Console Log: https://pastebin.com/q2LprbZf

Here's a gif of the bug: https://im5.ezgif.com/tmp/ezgif-5-7fba54991f27.gif

**Comment by gliscowo** [comment]
I sadly couldn't reproduce the issue at all and the log isn't heplful either, so it's probably some incompatibility on your end. I would first ask you to test without any other mods and if that fixes it, try to figure out which mod is causing the problem. The process would probably be quicker if you re-joined the discord so we could talk about it easier
Cheers

**Comment by ConqAra** [comment]
Found the incompatibility. Notenoughanimations & the Transliterlationlib that comes with it causes a weird incompatibility that causes a failed chunk error when interacting with the gem tinkerer while a totem of undying is in your offhand.

**Comment by gliscowo** [comment]
Have you tested whether this only happens with totems?

**Comment by ConqAra** [comment]
yeah I have, I've tried with shield, and other things. It's only totem of undying.

**Comment by gliscowo** [comment]
As there have been no other reports of this problem and due to inactivity here I will close this
