### ISSUE TITLE
Pickaxe right click doesn't work with Modern Industrialization ore (1.17.2)

### ISSUE THREAD

**Issue by ZeekDaGeek** [glisco03/conjuring#18]
The Soul Pickaxe's right click ability doesn't work with Modern Industrialization ore and  there doesn't appear to be a way to add new ores.

Possible fixes:
- Make it so the pickaxe works with any block that has a specific Tag so that you can add/remove blocks to the list
- Have a whitelist in the configs.

**Comment by gliscowo** [comment]
Fixed in f584f235 with a general approach that checks the name of the block class for `OreBlock`, will be released soon in 1.0.10
