### ISSUE TITLE
Creeper just exploded

### ISSUE THREAD

**Issue by magicaton** [glisco03/conjuring#2]
[crash-2021-03-07_19.08.39-server.txt](https://github.com/glisco03/conjuring/files/6097588/crash-2021-03-07_19.08.39-server.txt)
[crash-2021-03-07_19.08.57-server.txt](https://github.com/glisco03/conjuring/files/6097590/crash-2021-03-07_19.08.57-server.txt)
[crash-2021-03-07_19.10.57-server.txt](https://github.com/glisco03/conjuring/files/6097591/crash-2021-03-07_19.10.57-server.txt)

**Comment by glisco03** [comment]
Heyo, I would very much like to help you, but currently I just have too little information. Could you tell me under what specific circumstances the crash happens?

**Comment by magicaton** [comment]
> Heyo, I would very much like to help you, but currently I just have too little information. Could you tell me under what specific circumstances the crash happens?

Sorry, I thought that everything was written in the logs. I caught the creeper and began the ritual. And inadvertently came too close, the creeper exploded and the world crashed. I had to uninstall the mod to enter the world.
