### ISSUE TITLE
Errors in Conjuring Enchiridion - 1.18 Snapshot

### ISSUE THREAD

**Issue by ClaudiusMinimus** [glisco03/conjuring#21]
In testing, the build conjuring-2.0.0+pre1.jar for 1.18 Snapshot, _the Conjuring Enchiridion_ crafts fine, but I cannot open it to read. There are no errors, it just does nothing.

Edited: forgot to add "the Conjuring Enchiridion" when originally posting this.

**Comment by ClaudiusMinimus** [comment]
I see this issue is Patchouli and likely not Conjuring.

**Comment by ClaudiusMinimus** [comment]
I posted on the Patchouli discord and found that Patchouli is working fine. While looking at the logs I found there are several errors preventing the Conjuring Enchiridion from loading.

[latest.log](https://github.com/glisco03/conjuring/files/7455953/latest.log)

**Comment by gliscowo** [comment]
Fixed in latest
