### ISSUE TITLE
Stabelized conjuring focus does not keep working when not nearby

### ISSUE THREAD

**Issue by EmreCaylar** [glisco03/conjuring#32]
so i have been using this mod for xp farms. when I used a stabilized conjuring focus it should act as a player too, but it doesn't anymore. This has begun since the modpack had been updated, we went from All of Fabric 0.2.5 to 0.2.9. Somewhere in the changelog it was stated that and I quote "Nerfed Conjuring values by 100%." Does this issue have something to do with all of fabric or conjuring?

**Comment by gliscowo** [comment]
Is the chunk with the Conjurer in it being force-loaded by a chunkloader or similar means? If that is not, the Conjurer can't possibly continue to work

**Comment by EmreCaylar** [comment]
nvm i have found the issue, it was something else causing it

**Comment by gliscowo** [comment]
Would you mind telling me what is was? If there's some issue with this I'd still like to fix it
Cheers

**Comment by EmreCaylar** [comment]
so first i was using fans, which stop working when not nearby, it got fixed when I replaced it with water. after a while the owner decided to disable chunkloader. I'm usually 100 blocks above the conjurer, shouldn't it still work cause it doesn't?
