### ISSUE TITLE
Wither Skeleton Spawner

### ISSUE THREAD

**Issue by Piceousx** [glisco03/conjuring#33]
The wither skeleton spawner only works in the Nether Fortress Bounding Box and nowhere else. I was wondering if this could be adjusted to make it a bit more useful outside of the nether. Thank you.

Playing with the "Medieval Minecraft Modpack"

**Comment by gliscowo** [comment]
At least in my experience using Conjuring in a lot of different setups, I have definitely been able to spawn Wither Skeletons in areas outside of a Nether Fortress. You do of course have to make sure it is dark enough for them, if you can't get it to work it would be good to provide more context so we can go about reproducing your exact situation
Cheers

**Comment by gliscowo** [comment]
Have you been able to figure it out?

**Comment by kulcris** [comment]
i am having a similar issue, 

i have attached my setup and no wither skeletons are spawning 

![image](https://user-images.githubusercontent.com/2667394/151822375-d69c4b64-55f7-4fb2-8d72-c0c67dd70114.png)
![image](https://user-images.githubusercontent.com/2667394/151822411-912b2f9c-4782-4424-94f9-e5566b05daf6.png)


(latest attempt i used an egg to put wither into focus. not sure if that matters)

**Comment by kulcris** [comment]
![image](https://user-images.githubusercontent.com/2667394/151822611-a1f00537-ef7b-45da-8e41-7682879924e7.png)

**Comment by kulcris** [comment]
One more thing (sorry for spam) 

My nephew has the same setup in a slightly bigger room that works with wither skeles

**Comment by kulcris** [comment]
New observations 
Created a spawner in another dim and it worked. 
Nephews spawner stopped working. 

Its acting like only 1 is allowed per server

**Comment by kulcris** [comment]
Latest version seems to have this fixed. sorry for the spam from me

**Comment by kulcris** [comment]
Last comment i will make on this as i have given up getting it to work

It seems the "npc limit" has been hit as this does not work at the same time normal spawners dont work. 
i /kill @e to remove the world of any hidden mobs and that still did not fix the issue

**Comment by nathan-logan** [comment]
I found I was also having this issue, my problem was that I was using the Big Torch from [Kibe](https://www.curseforge.com/minecraft/mc-mods/kibe) which blocks mobs spawning in the dark, however the big torch still allows mobs to spawn on Cursed Dirt so thought it might not be a problem with the Conjurer which would've been nice 😄

**Comment by kulcris** [comment]
.... This may actually be it. My nephew had a big torch when this was
happening

**Comment by gliscowo** [comment]
Given that everbody who had problems seems to have fixed them and the original author hasn't responded in 2 months, I'll go ahead and close this as invalid, especially as every single time someone has reported a problem like this until now it was related to the Big Torch or a similar spawn-blocking gizmo
Cheers
