### ISSUE TITLE
Spawner drops the focus

### ISSUE THREAD

**Issue by Foresteam** [glisco03/conjuring#35]
Spawner drops the stabilized focus i insert into it after several spawns. It also emits a chest sound. I am building a creeper farm.
My mods:
* AE2WTLib-11.0.0-alpha.1
* appliedenergistics2-11.0.0-alpha.3
* architectury-4.1.44
* bitsandchisels-2.6.7
* cloth-api-3.2.64
* cloth-config-6.2.57-fabric
* collective-fabric-1.18.x-4.26
* conjuring-1.0.22+1.18
* custom-portals-3.0.1
* DetailArmorBar-2.6.2+1.18-fabric
* eldritch-mobs-1.11.0
* elementalcreepers-1.4.2+1.18.2
* endermangrief-1.18.2
* EnhancedQuarries-1.18.2-1.2.1
* enriched-2.3.0
* expandedstorage-7.3.11+1.18.2
* fabric-api-0.50.0+1.18.2
* FallingTree-1.18.2-3.5.0b1
* geckolib-fabric-1.18-3.0.36
* haha-funny-weed-0.1.2
* Highlighter-1.18-fabric-1.1.2
* HWGMod-1.18.2-1.1.5
* iammusicplayer-fabric-1.18.2-3.10
* Iceberg-1.18.2-fabric-1.0.38
* imperishable-items-fabric-mc1.18.1-2.1.2
* improvedmobs-1.18.2-1.10.7-fabric
* indium-1.0.2+mc1.18.2
* IngredientExtensionAPI-fabric-1.18.2-2.0.5
* InventorySorter-1.8.6-1.18
* iris-mc1.18.2-1.2.2-build.32
* ItemBorders-1.18-fabric-1.1.5
* journeymap-1.18.2-5.8.1beta3-fabric
* kubejs-fabric-1802.5.1-build.331
* lenientdeath-1.18.2-0.8.0
* libblockattributes-all-0.10.2
* lightest-lamps-fabric-1.0.0
* litematica-fabric-1.18.2-0.11.2
* lithium-fabric-mc1.18.2-0.7.9
* malilib-fabric-1.18.2-0.12.1
* Modern-Industrialization-1.1.0-alpha.01
* modmenu-3.1.0
* ninjaphenix-container-library-1.3.0+1.18-fabric
* OfflineSkins-1.18.2-v1-fabric
* otyacraftengine-fabric-1.18.2-2.14
* owo-lib-0.6.0+1.18
* PipePlus-1.18.2-0.4.1
* randommobeffects-fabric_1.18.x-1.6
* redstone-bits-1.7.1+fabric-mc1.18.2
* rer-2.5.0
* rhino-fabric-1801.1.9-build.135
* RoughlyEnoughItems-8.1.444
* RoughlyEnoughProfessions-fabric-1.18.2-1.0.1
* SimpleBackpack_Fabric-1.18.2-1.2.35
* simplepipes-all-0.7.2
* sodium-fabric-mc1.18.2-0.4.1+build.15
* starlight-1.0.2+fabric.89b8d9f
* TechReborn-5.2.0-beta.2
* tenshilib-1.18.2-1.6.6-fabric
* worldedit-mod-7.2.10
* WorldEditCUI-1.18.2+01
* wthit-fabric-4.8.1

**Comment by Noaaan** [comment]
What was causing the issue?

**Comment by Foresteam** [comment]
improvedmobs, as i remember. It changed the behavior of mobs, so they could steal items from containers. I adjusted the config.
