### ISSUE TITLE
Quilt support

### ISSUE THREAD

**Issue by Trnrr** [glisco03/conjuring#38]
quiltmc.org/

Just wanted to ask if Quilt support is planned for later releases. Most Fabric mods work on quilt but I tried the latest 1.18.2 version with quilt and it crashes.

If it's not planned, feel free to close the ticket. Have a good day.

**Comment by BasiqueEvangelist** [comment]
Could you send the crash report?

**Comment by gliscowo** [comment]
I can only second this, as I have not been able to reproduce this problem in testing
Cheers

**Comment by Trnrr** [comment]
Sorry when I made this I was on my phone and forgot to update it and add the log. I will take as look after work today and send the crash report if I can reproduce it again.

**Comment by Trnrr** [comment]
I took a better look at the error message and it said something like missing class & "owo". Figured owo was a dependency and downloaded that and it worked. Sorry about it, didn't know it was a dependency since it isn't listed on the Modrinth page and we can't see them yet without calling the api.
