### ISSUE TITLE
1.18.2 Backport

### ISSUE THREAD

**Issue by itsdinkd** [glisco03/conjuring#39]
1.19 is such a small update. I will be keeping Another Quality modpack 2 on 1.18.2, as well as other modpacks for the time being. Can you please backport your 1.19 change into 1.18.2? (Patchouli update)? This guide would be great to have. thanks

**Comment by Noaaan** [comment]
Patchouli integration should be present in Conjuring 1.0.22+1.18 (only available on CF)
If not then we could easily release a fix for it

**Comment by Noaaan** [comment]
https://www.curseforge.com/minecraft/mc-mods/conjuring/files/3693350
