### ISSUE TITLE
version 0.2.1 on server

### ISSUE THREAD

**Issue by Monster-Zer0** [glisco03/conjuring#4]
causes server not to boot. using latest frapi.

I think it's trying to run client side code on server.

https://paste.alloffabric.com/uliyekahuj.sql

**Comment by glisco03** [comment]
Thank you for reporting this. As you have correctly noted, I have once again been am idiot and not separated Client-Server code correctly. I'll make sure to to fix it asap

**Comment by glisco03** [comment]
Fixed in 0.2.2
