### ISSUE TITLE
opening the enchiridion crashes your game

### ISSUE THREAD

**Issue by diamondkinger** [glisco03/conjuring#40]
everytime i open the enchriridion book, it crashes my game

this is the error i get with it

The game crashed whilst unexpected error
Error: java.lang.NoClassDefFoundError:
vazkii/patchouli/common/book/BookRegistry
Exit Code: -1

**Comment by Wehrmachtserdbeere** [comment]
Can confirm, happens every time with the same error.

**Comment by Noaaan** [comment]
What version of Conjuring and Patchouli are you using? It seems like Patchouli might have changed some important class names

**Comment by Wehrmachtserdbeere** [comment]
I use Conjuring 1.0.23 without Patchouli

**Comment by diamondkinger** [comment]
same, i also use 1.0.23 (which im pretty sure is for minecraft 1.19 which is what im using)

**Comment by Noaaan** [comment]
There was an oversight when porting Conjuring for trying to load Patchouli, but a 1.19 version is available as a snapshot on their [Maven](https://maven.blamejared.com/vazkii/patchouli/Patchouli/1.19-70-FABRIC-SNAPSHOT/Patchouli-1.19-70-FABRIC-20220608.160738-1.jar). You can download it there.

It seems a bit pointless to make a release disabling Patchouli, only to re-enable it in the (possibly near) future. 
For now you will simply have to install Patchouli or remove the Enchiridion somehow (datapack to remove recipe or kubejs would work)

**Comment by gliscowo** [comment]
Given that there is no real problem apart from Patchouli not being declared as a dependency, I will close this issue for now and pin it to prevent future confusion. Check the above comment from Noaaan for where to download 1.19 builds of Patchouli
Cheers
