### ISSUE TITLE
Can't seem to get Heads?

### ISSUE THREAD

**Issue by FearlessDrifts** [glisco03/conjuring#41]
I tried using a conjurer in the conjuring mod and I did everything correctly watched several guides on how to do it and I got it working with each of the charms and with the Stabilized Conjuring Focus with a wither skeleton soul, the spawner works perfectly as it should except I am unable to get wither skeleton skulls from the spawner, is this a feature or is it bugged?

**Comment by Noaaan** [comment]
I am not able to re-produce this issue, and we do not modify any loot tables of any mobs spawned from the Conjurer. 
I am closing this as invalid.
