### ISSUE TITLE
[1.18.2] Silk Touch Spawners + Conjuring = Unlimited Essence

### ISSUE THREAD

**Issue by itsdinkd** [glisco03/conjuring#42]
as title suggests, if you use a mod to enable silk touch spawners, you can easily get essence by silk touching the spawner and continuously placing it and breaking it over and over again. 

Should modify the code that drops the essence loot table to have a condition that the player does not have silk touch on the breaking tool

**Comment by gliscowo** [comment]
As the 1.18 support cycle has ended quite some weeks ago, this change will not be backported to 1.18 - however in the [new 1.19 release](https://modrinth.com/mod/conjuring/version/YQZnkMDA) you can now enable Silk Touch behavior in the config
Cheers

**Comment by itsdinkd** [comment]
> As the 1.18 support cycle has ended quite some weeks ago, this change will not be backported to 1.18 - however in the [new 1.19 release](https://modrinth.com/mod/conjuring/version/YQZnkMDA) you can now enable Silk Touch behavior in the config Cheers

Why would you end support when most major modpacks that use your mod are still on 1.18.2, including mine, Another Quality modpack 2. 

I'd really appreciate it if you could release a small patch to fix this bug

**Comment by gliscowo** [comment]
For one simple reason - we're a small team of people supporting a non-trivial amount mods in your limited spare time. We simply do not have the capacity to keep supporting old versions, and since this bug is less than critical the mitigation won't be backported
Thank you for understanding

**Comment by itsdinkd** [comment]
Sorry, but I do not understand. You are not wanting to support the version that is most used by your players. Looking at your downloads, only 67 thousand people updated to your first 1.19 version out of the 334k downloads you have on your latest 1.18.2 version.  From January to March when you released 3 updates for 1.18.2, you had 724k downloads. From June to August on your 1.19 updates, you had 112k downloads. it's apparent this version should not be dropped.

Getting infinite amounts of a resource widely used by the mod is critical. Though I don't mean to rant and understand being a small team. it's just me working on 2 large modpacks, running 6 servers and a large discord community all while raising 2 kids and having a full-time career, I totally understand not wanting to backport to a different version, however, the version you do not want to support is still new and is the widely used one.

I just don't see how releasing something you already added is such a problem and so time-consuming? the commit looks pretty small, would it require a lot of changes? If you still do not want to do this, then that's fine. Can you tell me how I would get around this? is removing the essence from spawners possible through other means?
