### ISSUE TITLE
[Feature Request] EMI Support

### ISSUE THREAD

**Issue by fzzyhmstrs** [glisco03/conjuring#43]
[EMI](https://github.com/emilyploszaj/emi) is a new Item-searching mod in the same vein as REI, JEI, etc. It would be awesome if you could add compat support for it!

**Comment by gliscowo** [comment]
While I do agree this would be quite useful, I'm not willing to accept the extra maintenance burden that is having the recipe viewer code duplicated while REI still has the absolute majority of the market share. If and when EMI becomes more widely used I will probably reconsider this, but for the time being this will have to be a no from me
Cheers
