### ISSUE TITLE
Enchiridion not opening

### ISSUE THREAD

**Issue by nixord** [glisco03/conjuring#44]
The book's not doing anything when I right-click it. Im doing this in the Hex MC Modpack and also its the 1.18.2 version of it (Conjuring 1, not 2). Any ideas?

**Comment by Noaaan** [comment]
Do you have a link to the modpacks page? As long as you have Patchouli installed the book should open.

**Comment by nixord** [comment]
Huh... It DOES have Patchouli but either way, here it is: https://modrinth.com/modpack/hexmc-modpack/version/2.1.0

**Comment by Noaaan** [comment]
Could you please post your `latest.log`? It should contain an error when you open an invalid book

**Comment by nixord** [comment]
Uhhh... Im still playing but havent tried to open it for a few days already.

**Comment by nixord** [comment]
Where can I find it?

**Comment by Noaaan** [comment]
https://fabricmc.net/wiki/player:tutorials:logs_ml:windows

**Comment by nixord** [comment]
nvm I think I found it
[latest.log](https://github.com/wisp-forest/conjuring/files/9291724/latest.log)

**Comment by nixord** [comment]
https://pastebin.com/vyuTSJkT

**Comment by BasiqueEvangelist** [comment]
AFAIK the Patchouli compat was broken in 1.0.21+1.18, so you should probably upgrade Conjuring to 1.0.22+1.18

**Comment by nixord** [comment]
Also just know that the game doesnt crash. It just does the animation of using an item with the left click but nothing else happens when i try to open the Enchiridion.

**Comment by nixord** [comment]
> AFAIK the Patchouli compat was broken in 1.0.21+1.18, so you should probably upgrade Conjuring to 1.0.22+1.18

Huh? 
![image](https://user-images.githubusercontent.com/45505384/183681232-1e634617-e330-4690-81ea-667302200ace.png)

But the only 1.0.22 is the Conjuring 2, not 1.

**Comment by Noaaan** [comment]
This does not matter, as its a badly named version. Please update

**Comment by nixord** [comment]
Ok! Thanks guys! Im gonna try that now and if it fixes it, ill close the issue.

**Comment by nixord** [comment]
Indeed it works now! Thanks a lot again and... CLOSED!

**Comment by nixord** [comment]
... Actually Idk how to close it but its definitely close-able now.

**Comment by gliscowo** [comment]
![image](https://user-images.githubusercontent.com/15788224/183701543-65a83f92-e64c-468d-88fa-ac7c36a35a00.png)
This button would have been your best friend, but fret not, I've now done it for you
Cheers
