### ISSUE TITLE
Stabilized Focus Extraction Not Working

### ISSUE THREAD

**Issue by cdburgess** [glisco03/conjuring#45]
Based on the enchiridion, we can cleanse a stabilized focus. According to the book, it says:
"The focus to be cleaned must be placed into a Soul Funnel and the Distilled Spirit dropped on top."

I have tried everything the Enchiridion suggests for cleansing a stabilized focus and cannot get it to work. Here are all of the things I have tried with the funnel:
- place soul sand and then the stabilized focus, when I click with the distilled spirit, it ejects the focus
- no soul sand and trying to place the focus (or distilled spirit) it will not place

It appears this is not coded currently or something is broken and it doesn't work as described. Is this a bug?

I downloaded the 1.19 code and I am running it stand alone from Intellij to ensure there are no other mod conflicts

**Comment by Noaaan** [comment]
Are you sure this does not work? In the book it says this: 
![image](https://user-images.githubusercontent.com/4163353/184007969-7e67e0db-f735-4012-8364-cd0b0febd443.png)

**Comment by cdburgess** [comment]
How do I get the distilled spirit involved? Like a slash potion?

**Comment by cdburgess** [comment]
I can place the focus but it until I can "drop on top" the distilled spirit, the wand doesn't work. How do I get the distilled spirit involved? Like a splash potion? I can't even throw the distilled spirit to do so. So yes, I have tried a "right-click with the conjuring scepter" and it does nothing. Most likely because the distilled spirit is not involved. So I guess what I am looking for is a step-by-step on how to get this to work if it is working correctly. Because the book is not explaining it very clearly.

**Comment by gliscowo** [comment]
You're simply overcomplicating it - all you have to do is drop the distilled spirit item onto the funnel, as in literally dropping it on top with your drop key

**Comment by cdburgess** [comment]
Yep! I was overcomplicating it. I didn't realize it literally meant drop. I was so used to the way everything else was working, I didn't expect that. Thanks for the help.
