### ISSUE TITLE
Recipe Integration with EMI Compat mod

### ISSUE THREAD

**Issue by ConqAra** [glisco03/conjuring#48]
Add EMI Support for conjuring recipes, I know this might seem redundant because of REI but a lot more people have been starting to use EMI now, there's already a mod for EMI called EMI Compat which add other mod compatibility to EMI. They recommended me to ask you first if you will add support for EMI.

[Requested with Emi Compat author ](https://github.com/Chikage0o0/EMICompat/issues/2)

**Comment by gliscowo** [comment]
Duplicate of #43
