### ISSUE TITLE
Ignorance Gem Don't Working for Swords

### ISSUE THREAD

**Issue by FruynGames** [glisco03/conjuring#49]
I'm using Conjuring Forgery 0.2.2, Minecraft 1.16.5 and Forge 36.2.34. I'm not using any more mods (only hwyla to see the damage).
The soul alloy sword makes less damage with each ignorance gem it has. With three ignorance gems, it makes less damage than a diamond sword. Also i think that the skill to ignore armor from mobs doesn't work, but i can be wrong.

**Comment by gliscowo** [comment]
While I appreciate you taking the time to report these problems, I'm sorry to say that we do not provide support for Minecraft versions below 1.19 anymore. Especially Forgery is now almost 1.5 years old and has long passed its support cycle. I'd genuinely like to help you get your game running smoothly, but we simply do not have the resources to provide support reaching this far back. 

Thank you for understanding and have a great day
