### ISSUE TITLE
Bugged description

### ISSUE THREAD

**Issue by FruynGames** [glisco03/conjuring#50]
I'm using Conjuring Forgery 0.2.2, Minecraft 1.16.5 and Forge 36.2.34. 
When you have a tool with an aspect gem, the description have a strange A.
![2022-10-16_19 27 09](https://user-images.githubusercontent.com/99764309/196061453-9605f16f-7177-4189-b4e7-1556131009a7.png)

**Comment by gliscowo** [comment]
See #49
