### ISSUE TITLE
A crash occurred when I opened the Creative Items list(1.19.2 Fabric)

### ISSUE THREAD

**Issue by DarkCrystalll** [glisco03/conjuring#51]
I don't know why
[minecraft-exported-crash-info-2022-11-27T05-28-07.zip](https://github.com/wisp-forest/conjuring/files/10097070/minecraft-exported-crash-info-2022-11-27T05-28-07.zip)

**Comment by gliscowo** [comment]
Fixed in [1.0.26](https://modrinth.com/mod/conjuring/version/GrBHP1v7)
