### ISSUE TITLE
Soul Alloy Pickaxe secondary ability and Spectrum Block Breaking issue

### ISSUE THREAD

**Issue by fzzyhmstrs** [glisco03/conjuring#56]
There may be a similar issue with other tools' secondary abilities, but the pickaxe was the tool this was seen with.

Spectrum adds ores that cloak themselves as stone/deepslate if you haven't unlocked them. If the block is locked, it drops stone/cobblestone, if it's unlocked it drops the gems/ores etc as it should.

When using the vein mining ability, the spectrum blocks drop as cobble even if they are unlocked to the player:

* Anticipated result: They vein drops the ores.
* Actual result: Cobble dropped

Looking through the source, `BlockCrawler` appears to the be source of the issue. the `BlockBreakingEntity` calls `crawl` when it hits a block, and the BlockCrawler makes its list of ore blocks and then calls on `WorldOps` from owo-lib to break them. The issue is, _the player context isn't passed_.

The BlockBreakingEntity has the owner entity available, so I believe that the BlockCrawler needs to accept and store the owner entity (or null if not available) in it's `CrawlData` to pass it as the breakingEntity to owo-lib.

From owo-lib, circled method is currently used. breakingEntity is needed as context:

![image](https://user-images.githubusercontent.com/72876796/235316031-5ec8bd7e-38d7-49f2-bac5-ead534ca4304.png)

**Comment by gliscowo** [comment]
Even though I forgot to mention it in the changelog, this has now been fixed in [1.0.28](https://modrinth.com/mod/conjuring/version/1.0.28+1.20)

Cheers
