### ISSUE TITLE
Conjurer spawning passive mobs not working

### ISSUE THREAD

**Issue by Imphalda** [glisco03/conjuring#57]
Not sure why, but regardless of charms or anything of the sort the conjurer is incapable of spawning passive mobs (chicken, sheep, cow, etc.). I'm playing with a self-made modpack for me and my brother and we are in 1.19.2 .

**Comment by gliscowo** [comment]
Exactly like a vanilla spawner, the Conjurer requires the [mob's spawn conditions to be met](https://docs.wispforest.io/faq/#my-conjurer-does-not-spawn-anything). In the case of passive mobs this means two things:
 - it has to be surrounded by grass
 - there needs to be sufficient light (level >7 I believe)
 
Does your setup meet those requirements?

**Comment by Imphalda** [comment]
This worked, thank you, thank you. We had it in a stone enclosure and it never occurred to me even when I tested in creative to try this. Thanks again.
