### ISSUE TITLE
Crash with mythic mobs spawner

### ISSUE THREAD

**Issue by TPNils** [glisco03/conjuring#58]
Hi,

I managed to create a Conjering Focus of a Żar-ptak, a mob from [mythic mounts](https://www.curseforge.com/minecraft/mc-mods/mythic-mounts) and when i put it in a Conjurer my client crashed with this log
[crash-2023-10-21_01.44.12-client.txt](https://github.com/wisp-forest/conjuring/files/13059305/crash-2023-10-21_01.44.12-client.txt)

While this is rather a bug related to mythic mounts, I would still like to mention it here as you may be interested to keep your mod as stable as possible, regardless of other mods.

**Comment by TPNils** [comment]
To clarify, I also made an issue with mythic mobs
https://legacy.curseforge.com/minecraft/mc-mods/mythic-mounts/issues/131

**Comment by gliscowo** [comment]
As you correctly mentioned, this problem lies with MythicMounts and not Conjuring - crashing here when the entity renderer crashes is correct behavior

Cheers
