### ISSUE TITLE
Conjuring or conflicting mod asking for optifine shaders and not loading (Fabric version) 

### ISSUE THREAD

**Issue by randomlyGenerated-0** [glisco03/conjuring#6]
I'm using Sodium, Lithium, and Phosphor, I've tried this on 2 different versions, version 2.3 and 2.0.
Log: (I'm not a developer and I might just be stupid) 
 
[latest.log](https://github.com/glisco03/conjuring/files/6576748/latest.log)

**Comment by Noaaan** [comment]
The log you provided is quite short, does your game simply not launch? Do you have any form of crash reports or something similar?
You are right there is some conflict as some mod is requesting optifine shaders. Conjuring does not do this, so this might be an issue with another mod. You could try disabling the replaymod and see if your game launches with it. You should also disable Conjuring and see if your game launches without it.

**Comment by randomlyGenerated-0** [comment]
I did both, Keep conjuring disabled replay, fixed optifine
Then I Disabled Conjuring and Kept replay, worked perfectly fine.

**Comment by randomlyGenerated-0** [comment]
Found out the problem, My fabric version, was literally 1 version away from the one that's compatible. It doesnt have a notification like forge that says "[mod] require forge version [newer version]. Your version is currently [old version]
