### ISSUE TITLE
[bug] [1.20.2] Soul Alloy Hatchet doesn't work with Better Combat mod

### ISSUE THREAD

**Issue by noawx** [glisco03/conjuring#60]
The Soul Alloy Sword & Soul Alloy Scythe work with the [Better Combat](https://modrinth.com/mod/better-combat) mod, but the Soul Alloy Hatchet doesn't.

Minecraft Version: 1.20.2
Mod Loader Version: Quilt Loader 0.21.2-beta.4
Conjuring Version: 1.0.28+1.20.2
Better Combat Version: 1.8.1+1.20.2

**Comment by gliscowo** [comment]
When you say "doesn't work", what do you mean exactly? This isn't really enough for me to go off, it could be broken in any number of ways

**Comment by noawx** [comment]
It acts like a vanilla axe without the special swing animations. (Like using a pickaxe/shovel/hoe with the Better Combat mod)
