### ISSUE TITLE
Ritual of Extraction fails on shulkers.

### ISSUE THREAD

**Issue by Suros** [glisco03/conjuring#65]
As the title says, it tries to run the ritual, but it simply doesn't work. It also jams up the soul funnel until broken. Guessing it has something to do with the immobile nature of shulkers, but I could be totally wrong. Also found that if I attempt to the start the ritual and then break the funnel, the shulker will proceed to die and it will consume the related drops on pedestals.

**Comment by gliscowo** [comment]
Thanks for reporting, this has now been fixed in [1.0.30 for 1.20.3/4](https://modrinth.com/mod/conjuring/version/1.0.30+1.20.3)
Cheers
