### ISSUE TITLE
Achievements Go Off When Any Item Is In Inventory

### ISSUE THREAD

**Issue by queenofmillers** [glisco03/conjuring#8]
Having any item in the inventory (may specifically be in hand) causes 9 achievements.  Happened when I was in creative mode so I do not know if it affects survival. 

Achievements:
[A Quite Spiritual Substance]
[Soul Forgery]
[A new Beginning]
[Spiritual Implements]
[Focal Point]
[Not Suited For Jewelry]
[Staff of Office]
[Psychic Braiding]
[Prestidigitator]

Mod Version: [1.17-pre4] Conjuring 2 - 1.0.1

**Comment by glisco03** [comment]
Maybe actually closing this back when I fixed it might have been a good idea.

Anyways, it's fixed
